import { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" dark text-foreground bg-background">
      <body className="flex flex-col min-h-screen">
        <NextUIProvider>
          <main className="flex-grow flex flex-col">{children}</main>
        </NextUIProvider>
      </body>
    </html>
  );
}
